name: CI-CD

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install packages
        run: yarn install
      - name: ESLint
        run: yarn lint
